import { run_event_repository_append_and_load_tests, run_event_repository_rename_tests, run_event_repository_validation_tests, run_event_repository_last_sessions_tests, run_event_repository_dedupe_tests, run_event_repository_malformed_preservation_tests, run_event_repository_line_index_tests, run_event_repository_replication_tests, run_event_repository_dup_store_dedup_tests } from "./test_event_repository";
import { run_session_happy_path_tests, run_session_invalid_transition_tests, run_session_elapsed_open_segment_tests, run_session_equality_tests } from "./test_session";
import { run_event_collection_tests } from "./test_event_collection";
import { run_event_collection_extended_tests } from "./test_event_collection_extended";
import { run_job_repository_tests } from "./test_jobs";
import { run_dashboard_buildPayload_tests, run_dashboard_filterRelevantErrors_tests, run_dashboard_replaceEvent_tests, run_dashboard_editRoundTrip_tests } from "./test_dashboard";
import { run_event_tests } from "./test_event";
import { run_job_domain_tests } from "./test_job";
import { run_job_collection_tests } from "./test_job_collection";
import { run_build_info_tests } from "./test_build_info";
import { run_resolve_storage_dir_tests } from "./test_paths";
import { run_filter_state_tests } from "./test_filter_state";
import { run_split_concatenated_jsonl_tests, run_sanitize_lines_tests, run_append_line_safe_tests, run_write_file_atomic_tests, run_write_helpers_mkdir_tests, run_repository_sanitized_load_tests, run_compact_log_tests } from "./test_log_hygiene";
import { run_repo_config_tests, run_repo_config_exclusive_tests, run_repo_config_fallback_tests } from "./test_repo_config";
import { run_derive_repo_jobs_tests, run_ensure_repo_jobs_cache_tests } from "./test_repo_jobs";
import { run_registry_domain_tests, run_registry_repository_tests, run_registry_declined_tests, run_registry_remove_declined_noop_tests, run_registry_repository_update_tests } from "./test_registry";
import { run_local_opt_in_tests, run_local_opt_in_decline_tests, run_local_opt_in_first_opt_in_race_tests, run_local_opt_in_concurrent_writer_tests } from "./test_local_opt_in";
import { run_append_owned_event_tests, run_rebuild_index_tests, run_registry_log_paths_tests } from "./test_global_index";
import { run_migration_tests } from "./test_migration";
import { run_instance_lock_tests, run_instance_lock_exclusive_first_acquire_tests, run_instance_lock_fallback_tests } from "./test_instance_lock";
import { run_multi_instance_no_crosstalk_tests, run_multi_instance_index_convergence_tests } from "./test_multi_instance";

async function main() {
    try {
        run_event_repository_append_and_load_tests();
        run_event_repository_rename_tests();
        run_event_repository_validation_tests();
        run_event_repository_last_sessions_tests();
        run_event_repository_dedupe_tests();
        run_event_repository_malformed_preservation_tests();
        run_event_repository_line_index_tests();
        run_event_repository_replication_tests();
        run_event_repository_dup_store_dedup_tests();
        run_session_happy_path_tests();
        run_session_invalid_transition_tests();
        run_session_elapsed_open_segment_tests();
        run_session_equality_tests();
        run_event_collection_tests();
        run_event_collection_extended_tests();
        run_event_tests();
        run_job_domain_tests();
        run_job_collection_tests();
        await run_job_repository_tests();
        run_dashboard_buildPayload_tests();
        run_dashboard_filterRelevantErrors_tests();
        run_dashboard_replaceEvent_tests();
        run_dashboard_editRoundTrip_tests();
        run_build_info_tests();
        run_resolve_storage_dir_tests();
        run_filter_state_tests();
        run_split_concatenated_jsonl_tests();
        run_sanitize_lines_tests();
        run_append_line_safe_tests();
        run_write_file_atomic_tests();
        run_write_helpers_mkdir_tests();
        run_repository_sanitized_load_tests();
        run_compact_log_tests();
        run_repo_config_tests();
        run_repo_config_exclusive_tests();
        run_repo_config_fallback_tests();
        run_derive_repo_jobs_tests();
        run_ensure_repo_jobs_cache_tests();
        run_registry_domain_tests();
        run_registry_repository_tests();
        run_registry_declined_tests();
        run_registry_remove_declined_noop_tests();
        run_registry_repository_update_tests();
        run_local_opt_in_tests();
        run_local_opt_in_decline_tests();
        run_local_opt_in_first_opt_in_race_tests();
        run_local_opt_in_concurrent_writer_tests();
        run_append_owned_event_tests();
        run_rebuild_index_tests();
        run_registry_log_paths_tests();
        run_migration_tests();
        run_instance_lock_tests();
        run_instance_lock_exclusive_first_acquire_tests();
        run_instance_lock_fallback_tests();
        run_multi_instance_no_crosstalk_tests();
        run_multi_instance_index_convergence_tests();
        console.log("All tests passed.");
        process.exit(0);
    } catch (err) {
        console.error("Tests failed:", err);
        process.exit(1);
    }
}

main();
