/**
 * Writes out/buildinfo.json — { version, commit, branch, build_date } — so
 * TimeScope can show which build is running, both packaged (.vsix) and
 * during F5 dev sessions.
 *
 * Run as part of `npm run vscode:prepublish`, after compile (out/ must
 * exist), so it's regenerated by every compile — F5, `npm test`, and
 * `npm run package` all get a current file, never a stale one from a
 * previous run.
 *
 * Git failures (e.g. packaging from a source tree with no .git, such as a
 * tarball export) degrade to "unknown" fields rather than failing the
 * build — build info is best-effort display, never load-bearing.
 */

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const OUT_PATH = path.resolve(__dirname, "..", "out", "buildinfo.json");
const { version } = require("../package.json");

function git(args) {
    try {
        return execFileSync("git", args, { cwd: path.resolve(__dirname, ".."), encoding: "utf8" }).trim();
    } catch (err) {
        console.warn(`write_buildinfo: git ${args.join(" ")} failed (${err.message}); using "unknown"`);
        return "unknown";
    }
}

const buildInfo = {
    version,
    commit: git(["rev-parse", "HEAD"]),
    branch: git(["rev-parse", "--abbrev-ref", "HEAD"]),
    build_date: new Date().toISOString(),
};

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, JSON.stringify(buildInfo, null, 2), "utf8");

console.log(`Wrote ${OUT_PATH}: v${buildInfo.version} @ ${buildInfo.commit.slice(0, 7)}`);
